<template>
  <div class="modern-page">
    <section class="modern-hero">
      <h1>Produtos</h1>
      <p>Produtos vêm da base de dados. O gestor pode criar e aprovar os produtos da sua instituição para aparecerem no simulador.</p>
      <div class="hero-actions"><button class="btn btn-primary" @click="openCreate">+ Novo produto</button><button class="btn" @click="load">Actualizar</button></div>
    </section>
    <div class="modern-card"><table class="modern-table"><thead><tr><th>Produto</th><th>Faixa</th><th>Taxa mensal</th><th>Mora diária</th><th>Prazo</th><th>Estado</th><th>Descrição</th><th>Acções</th></tr></thead><tbody><tr v-for="p in products" :key="p.id"><td><strong>{{p.name}}</strong><br><span class="muted">{{p.Institution?.name}}</span></td><td>{{mzn(p.min_amount)}} – {{mzn(p.max_amount)}}</td><td>{{percent(p.interest_rate)}}</td><td>{{percent(p.late_fee_rate)}}</td><td>{{p.min_term_months}}–{{p.max_term_months}} meses</td><td><StatusBadge :status="p.status==='active'&&p.is_visible?'active':'pending'" /></td><td>{{p.description||'—'}}</td><td><button class="btn btn-sm btn-primary" :disabled="p.status==='active'&&p.is_visible" @click="approve(p)">Aprovar</button></td></tr><tr v-if="!products.length"><td colspan="8" class="empty-state">Sem produtos na base de dados.</td></tr></tbody></table></div>
    <div v-if="modal" class="modal-backdrop" @click.self="modal=false"><div class="mk-modal wide"><div class="mk-modal-head"><h2>Novo produto</h2><button class="modal-x" @click="modal=false">×</button></div><form @submit.prevent="save"><div class="form-grid"><label class="field"><span>Nome do produto</span><input class="input" v-model="form.name" required></label><label class="field"><span>Valor mínimo</span><input class="input" type="number" v-model.number="form.min_amount" required></label><label class="field"><span>Valor máximo</span><input class="input" type="number" v-model.number="form.max_amount" required></label><label class="field"><span>Taxa mensal (%)</span><input class="input" type="number" step="0.01" v-model.number="form.rate_percent" required></label><label class="field"><span>Juros de mora diária (%)</span><input class="input" type="number" step="0.01" v-model.number="form.late_fee_percent" required></label><label class="field"><span>Prazo mínimo</span><input class="input" type="number" v-model.number="form.min_term_months" required></label><label class="field"><span>Prazo máximo</span><input class="input" type="number" v-model.number="form.max_term_months" required></label></div><label class="field full"><span>Descrição mínima</span><textarea class="input" v-model="form.description"></textarea></label><div class="modal-actions"><button class="btn" type="button" @click="modal=false">Cancelar</button><button class="btn btn-primary" type="submit">Gravar como pendente</button></div></form></div></div>
  </div>
</template>
<script setup>
import { ref,onMounted } from 'vue'; import { useToast } from 'vue-toastification'; import api from '@/services/api'; import StatusBadge from '@/components/common/StatusBadge.vue'
const toast=useToast(); const products=ref([]), modal=ref(false); const form=ref({name:'',description:'',min_amount:null,max_amount:null,rate_percent:null,late_fee_percent:0.5,min_term_months:1,max_term_months:12}); const mzn=v=>Number(v||0).toLocaleString('pt-MZ',{style:'currency',currency:'MZN',maximumFractionDigits:0}); const percent=v=>(Number(v||0)*100).toFixed(2)+'%';
async function load(){try{const {data}=await api.get('/products/admin'); products.value=data.data||[]}catch(e){toast.error(e.response?.data?.message||'Erro ao carregar produtos')}} function openCreate(){form.value={name:'',description:'',min_amount:null,max_amount:null,rate_percent:null,late_fee_percent:0.5,min_term_months:1,max_term_months:12}; modal.value=true} async function save(){try{const payload={...form.value,interest_rate:Number(form.value.rate_percent)/100,late_fee_rate:Number(form.value.late_fee_percent)/100,required_documents:['bi','nuit','residence_certificate','bank_statement']}; delete payload.rate_percent; delete payload.late_fee_percent; await api.post('/products',payload); toast.success('Produto criado. Fica pendente até aprovação.'); modal.value=false; await load()}catch(e){toast.error(e.response?.data?.message||'Erro ao gravar produto')}}
async function approve(p){try{await api.post(`/products/${p.id}/approve`); toast.success('Produto aprovado e disponível no simulador.'); await load()}catch(e){toast.error(e.response?.data?.message||'Erro ao aprovar produto')}}
onMounted(load)
</script>
